version: 1.0.{build}

os: WMF 5

# Skip on updates to the readme
skip_commits:
  message: /readme*/

install:
  - ps: Write-Host "Build version :`  $env:APPVEYOR_BUILD_VERSION"
  - ps: Write-Host "Branch        :`  $env:APPVEYOR_REPO_BRANCH"
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force
  
build: false

test_script:
  - ps: |
      $ScriptAnalyzerRules = Get-ScriptAnalyzerRule -Severity Warning
      $ScriptAnalyzerResult = Invoke-ScriptAnalyzer -Path ".\CustomPSScriptAnalyzerRules\ExampleScript.ps1" -IncludeRule $ScriptAnalyzerRules
      If ( $ScriptAnalyzerResult ) {
        $ScriptAnalyzerResultString = $ScriptAnalyzerResult | Out-String
        Write-Warning $ScriptAnalyzerResultString
      }
      Export-NUnitXml -ScriptAnalyzerResult $ScriptAnalyzerResult -Path ".\ScriptAnalyzerResult.xml"

      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ScriptAnalyzerResult.xml))

      If ( $ScriptAnalyzerResult ) {        
        # Failing the build
        Throw "Build failed because there was one or more PSScriptAnalyzer violation. See test result for more information."
      }
